[project]
name = "dcpmessage"
version = "0.1.0"
description = "package for retrieving GOES DCS message data from LRGS servers."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "sphinx>=8.2.3",
]
